### PR TITLE
Adding support for SmartDocs integration

### PR DESCRIPTION
**Pull request by csevb10**
Adds support for SmartDocs import/render/delete with the developer portal. 

Adds a new class (APIModelMojo) and goal (apimodel) to support authentication and integration with the developer portal to create or update models, import openapi specs, render models, or delete models.

### CODE REVIEW

**Comment by ssvaidyanathan** [comment]
@csevb10 - thanks for the PR. Can you please include the README as well with detailed info on how it works and if possible include sample ?

**Comment by ssvaidyanathan** [comment]
@csevb10 - dont see the samples

**Comment by csevb10** [comment]
I added the DevPortal directory and documentation in the README on how to execute it. Is that not what you were looking for?

**Comment by csevb10** [comment]
This work has moved to https://github.com/apigee/apigee-smartdocs-maven-plugin

**Pull request closed without merging**
